### ISSUE TITLE
Wiki feedback 1

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892016team4#1]
@Hongyuanli @ocifico @luizcieslak 

Please add the preliminary work concerning the product backlog.

There are 2 sections called Product Backlog. Do a pass on reading the wiki.

Tools and communications should be complete already.

**Comment by scharffc** [comment]
@Hongyuanli @ocifico @luizcieslak

The name of the app is missing from the wiki!

**Comment by scharffc** [comment]
The description too.

**Comment by Hongyuanli** [comment]
@scharffc It is in the idea proposal, I did not realize that it has to be on the homepage

**Comment by luizcieslak** [comment]
@scharffc done! Thanks for the feedback.
