### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892016team4#18]
Demo

The demo was good and I look forward to the next one.

Retrospective

Please update the burndown chart. It is important to have some stats in addition.

APK

I could not execute the apk file. Can you check and let me know if it works for you?

Contributions

https://github.com/paceuniversity/CS3892016team4/graphs/contributors

@Hongyuanli @ocifico @luizcieslak

**Comment by luizcieslak** [comment]
@scharffc Thanks. The burndown chart is updated and I installed the apk in BlueStacks and it is working. Can you tell me which error appeared to you?

**Comment by scharffc** [comment]
Link to download?
